/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructuras_2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class P_Grafica extends javax.swing.JFrame {

    public P_Grafica() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_archivos = new javax.swing.JDialog();
        Archivo_guardar = new javax.swing.JLabel();
        Archivo_nuevo = new javax.swing.JLabel();
        Abrir_archivo = new javax.swing.JLabel();
        Archivos_salir = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Menu_campos = new javax.swing.JDialog();
        Listar_Campos = new javax.swing.JLabel();
        Nuevo_registro = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Nuevo_campos = new javax.swing.JDialog();
        Combo_tipo = new javax.swing.JComboBox<>();
        Tx_campo = new javax.swing.JTextField();
        BT_Agrega_campo = new javax.swing.JButton();
        Terminar_campos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        listar_campos = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        elim_campo = new javax.swing.JButton();
        mod_campo = new javax.swing.JButton();
        Agrega_campo = new javax.swing.JButton();
        Modificar_campos = new javax.swing.JDialog();
        tf_mod_campo = new javax.swing.JTextField();
        combo_tipo2 = new javax.swing.JComboBox<>();
        Termina_mod = new javax.swing.JButton();
        Agregar_campos = new javax.swing.JDialog();
        nombre_agregar = new javax.swing.JTextField();
        Boton_agregar = new javax.swing.JButton();
        Combo_Agrega = new javax.swing.JComboBox<>();
        Registros = new javax.swing.JDialog();
        crear_regis = new javax.swing.JToggleButton();
        listar_regis = new javax.swing.JToggleButton();
        buscar_regis = new javax.swing.JToggleButton();
        L_campos = new javax.swing.JLabel();
        L_archivos = new javax.swing.JLabel();
        Reindexar = new javax.swing.JLabel();
        utilidades = new javax.swing.JLabel();
        L_registro = new javax.swing.JLabel();
        L_salir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        L_Fondo = new javax.swing.JLabel();

        Menu_archivos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Archivo_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        Menu_archivos.getContentPane().add(Archivo_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        Archivo_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NuevoArchivo.png"))); // NOI18N
        Archivo_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Archivo_nuevoMouseClicked(evt);
            }
        });
        Menu_archivos.getContentPane().add(Archivo_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        Abrir_archivo.setForeground(new java.awt.Color(255, 255, 255));
        Abrir_archivo.setText("ABRIR ARCHIVO FALTA FOTO");
        Abrir_archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Abrir_archivoMouseClicked(evt);
            }
        });
        Menu_archivos.getContentPane().add(Abrir_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 90));

        Archivos_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Archivos_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Archivos_salirMouseClicked(evt);
            }
        });
        Menu_archivos.getContentPane().add(Archivos_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo archivos.jpg"))); // NOI18N
        Menu_archivos.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 650));

        Menu_campos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Listar_Campos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listarCampos.png"))); // NOI18N
        Listar_Campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Listar_CamposMouseClicked(evt);
            }
        });
        Menu_campos.getContentPane().add(Listar_Campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        Nuevo_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo campo.png"))); // NOI18N
        Nuevo_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nuevo_registroMouseClicked(evt);
            }
        });
        Menu_campos.getContentPane().add(Nuevo_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondocampos.jpg"))); // NOI18N
        Menu_campos.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 390));

        Combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Int", "String", "Char", "Boolean" }));

        Tx_campo.setText("Nombre del Campo");
        Tx_campo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tx_campoMouseClicked(evt);
            }
        });

        BT_Agrega_campo.setText("Agregar");
        BT_Agrega_campo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_Agrega_campoMouseClicked(evt);
            }
        });

        Terminar_campos.setText("terminar de agregar");
        Terminar_campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Terminar_camposMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Creacion de Campos");

        javax.swing.GroupLayout Nuevo_camposLayout = new javax.swing.GroupLayout(Nuevo_campos.getContentPane());
        Nuevo_campos.getContentPane().setLayout(Nuevo_camposLayout);
        Nuevo_camposLayout.setHorizontalGroup(
            Nuevo_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nuevo_camposLayout.createSequentialGroup()
                .addGroup(Nuevo_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Nuevo_camposLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5))
                    .addGroup(Nuevo_camposLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(Nuevo_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Nuevo_camposLayout.createSequentialGroup()
                                .addComponent(BT_Agrega_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Terminar_campos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Nuevo_camposLayout.createSequentialGroup()
                                .addComponent(Tx_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(Combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        Nuevo_camposLayout.setVerticalGroup(
            Nuevo_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nuevo_camposLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addGroup(Nuevo_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tx_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(Nuevo_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Agrega_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Terminar_campos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        elim_campo.setText("Eliminar");
        elim_campo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elim_campoMouseClicked(evt);
            }
        });

        mod_campo.setText("Modificar");
        mod_campo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mod_campoMouseClicked(evt);
            }
        });

        Agrega_campo.setText("Agregar");
        Agrega_campo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agrega_campoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(elim_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Agrega_campo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(mod_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(elim_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mod_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Agrega_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129))
        );

        listar_campos.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        tf_mod_campo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_mod_campoMouseClicked(evt);
            }
        });

        combo_tipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "String", "char", "boolean" }));
        combo_tipo2.setToolTipText("");

        Termina_mod.setText("Modificar");
        Termina_mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Termina_modMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Modificar_camposLayout = new javax.swing.GroupLayout(Modificar_campos.getContentPane());
        Modificar_campos.getContentPane().setLayout(Modificar_camposLayout);
        Modificar_camposLayout.setHorizontalGroup(
            Modificar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificar_camposLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tf_mod_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(combo_tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(Modificar_camposLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(Termina_mod)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Modificar_camposLayout.setVerticalGroup(
            Modificar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificar_camposLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(Modificar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_mod_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(Termina_mod)
                .addGap(40, 40, 40))
        );

        nombre_agregar.setText("Nombre del Campo");
        nombre_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombre_agregarMouseClicked(evt);
            }
        });

        Boton_agregar.setText("Agregar Campo");
        Boton_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_agregarMouseClicked(evt);
            }
        });

        Combo_Agrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Int", "String", "Char", "Boolean" }));

        javax.swing.GroupLayout Agregar_camposLayout = new javax.swing.GroupLayout(Agregar_campos.getContentPane());
        Agregar_campos.getContentPane().setLayout(Agregar_camposLayout);
        Agregar_camposLayout.setHorizontalGroup(
            Agregar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_camposLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(nombre_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(Combo_Agrega, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(Agregar_camposLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(Boton_agregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Agregar_camposLayout.setVerticalGroup(
            Agregar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_camposLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(Agregar_camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_Agrega, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(Boton_agregar)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        crear_regis.setText("Crear");
        crear_regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crear_regisMouseClicked(evt);
            }
        });

        listar_regis.setText("Listar");

        buscar_regis.setText("Buscar");
        buscar_regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscar_regisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegistrosLayout = new javax.swing.GroupLayout(Registros.getContentPane());
        Registros.getContentPane().setLayout(RegistrosLayout);
        RegistrosLayout.setHorizontalGroup(
            RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrosLayout.createSequentialGroup()
                .addGroup(RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrosLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(crear_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(listar_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrosLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(buscar_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        RegistrosLayout.setVerticalGroup(
            RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrosLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listar_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(buscar_regis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_campos.setBackground(new java.awt.Color(255, 255, 255));
        L_campos.setForeground(new java.awt.Color(255, 204, 102));
        L_campos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campos.png"))); // NOI18N
        L_campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_camposMouseClicked(evt);
            }
        });
        getContentPane().add(L_campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 130));

        L_archivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/File_Explorer_23583.png"))); // NOI18N
        L_archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_archivosMouseClicked(evt);
            }
        });
        getContentPane().add(L_archivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        Reindexar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arbol.png"))); // NOI18N
        Reindexar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReindexarMouseClicked(evt);
            }
        });
        getContentPane().add(Reindexar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        utilidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xml.png"))); // NOI18N
        utilidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilidadesMouseClicked(evt);
            }
        });
        getContentPane().add(utilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        L_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N
        L_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_registroMouseClicked(evt);
            }
        });
        getContentPane().add(L_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, -1, -1));

        L_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        L_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_salirMouseClicked(evt);
            }
        });
        getContentPane().add(L_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RICARDO ROMERO 11641137");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BRAULIO CALIX 11711133");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROYECTO ESTRUCTURAS DE DATOS II ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        L_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpg"))); // NOI18N
        getContentPane().add(L_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_salirMouseClicked
        JOptionPane.showMessageDialog(this, "Gracias por usar el mejor \nmanejador de archivos ;)");
        System.exit(0);
    }//GEN-LAST:event_L_salirMouseClicked

    private void L_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_registroMouseClicked
        Registros.setModal(true);
        Registros.pack();
        Registros.setLocationRelativeTo(this);
        Registros.setVisible(true);
    }//GEN-LAST:event_L_registroMouseClicked

    private void utilidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilidadesMouseClicked
        JOptionPane.showMessageDialog(this, "opcion no implementada..... aún ;)");
    }//GEN-LAST:event_utilidadesMouseClicked

    private void ReindexarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReindexarMouseClicked
        Arbol_B arbol = new Arbol_B();
        try {
            leer_archivo.Archivo10000(archivo);
            leer_archivo.arbol(arbol, archivo, metadata);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(P_Grafica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(P_Grafica.class.getName()).log(Level.SEVERE, null, ex);
        }
        arbol.imprimir_arblo(arbol.getRaiz(), 0);

    }//GEN-LAST:event_ReindexarMouseClicked

    private void L_archivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_archivosMouseClicked
        Menu_archivos.setModal(true);
        Menu_archivos.pack();
        Menu_archivos.setLocationRelativeTo(this);
        Menu_archivos.setVisible(true);
    }//GEN-LAST:event_L_archivosMouseClicked

    private void L_camposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_camposMouseClicked
        if (archivo == null) {
            JOptionPane.showMessageDialog(this, "no ha seleccionado ningun archivo...");
        } else {
            Menu_campos.setModal(true);
            Menu_campos.pack();
            Menu_campos.setLocationRelativeTo(this);
            Menu_campos.setVisible(true);
        }
    }//GEN-LAST:event_L_camposMouseClicked

    private void Archivo_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Archivo_nuevoMouseClicked
        JFileChooser fileChooser = new JFileChooser("./");
        fileChooser.setDialogTitle("Seleccione");
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            archivo = new File(fileChooser.getSelectedFile().getPath() + ".txt");

            if (!archivo.exists()) {
                try {
                    archivo.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(P_Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(Menu_archivos, "Archivo Creado");
            } else {
                JOptionPane.showMessageDialog(Menu_archivos, "Arhcivo con ese nombre ya existe");
            }
        }
        nuevo = true;
    }//GEN-LAST:event_Archivo_nuevoMouseClicked

    private void Tx_campoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tx_campoMouseClicked
        // TODO add your handling code here:
        Tx_campo.setText("");
    }//GEN-LAST:event_Tx_campoMouseClicked

    private void Nuevo_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nuevo_registroMouseClicked
        if (metadata.getNum_campos() == 0) {
            Nuevo_campos.setModal(true);
            Nuevo_campos.pack();
            Nuevo_campos.setLocationRelativeTo(this);
            Nuevo_campos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(Menu_campos, "ya se crearon los campos iniciales, ingrese al menu de la tabla");
        }
    }//GEN-LAST:event_Nuevo_registroMouseClicked

    private void Archivos_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Archivos_salirMouseClicked
        Menu_archivos.setVisible(false);
    }//GEN-LAST:event_Archivos_salirMouseClicked

    private void BT_Agrega_campoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Agrega_campoMouseClicked
        nuevo = false;
        System.out.println(Combo_tipo.getSelectedIndex());
        String campo = Tx_campo.getText();
        int pos = Combo_tipo.getSelectedIndex();
        String tipo = "";
        if (pos == 0) {
            tipo = "int";
        } else if (pos == 1) {
            tipo = "String";
        } else if (pos == 2) {
            tipo = "Char";
        } else if (pos == 3) {
            tipo = "boolean";
        }
        JOptionPane.showMessageDialog(Nuevo_campos, "Campo agregado con exito ");
        Tx_campo.setText("Nombre del Campo");
        temp.add(new Campos(campo, tipo));
    }//GEN-LAST:event_BT_Agrega_campoMouseClicked

    private void Terminar_camposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Terminar_camposMouseClicked
        String Mensaje = "";
        for (int i = 0; i < temp.size(); i++) {
            Mensaje += i + ") ";
            Mensaje += temp.get(i).toString();
            Mensaje += "\n";
        }
        int numero = -1;
        ArrayList temporal = new ArrayList();
        while (numero < 0 || numero > temp.size() - 1) {
            try {
                numero = Integer.parseInt(JOptionPane.showInputDialog(Nuevo_campos, "ingrese el numero del campo que desea que sea la llave: \n" + Mensaje));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        temporal.add(temp.get(numero));
        for (int i = 0; i < temp.size(); i++) {
            if (i == numero) {

            } else {
                temporal.add(temp.get(i));
            }
        }

        Metadata metas = new Metadata(temporal.size(), temporal);
        leer_archivo.escribir(metas, archivo);
        try {

            RandomAccessFile f = new RandomAccessFile(archivo, "rw");
            f.seek(200);
            f.writeBytes("400;");
            System.out.println("escribio");
        } catch (Exception e) {
        }
        Nuevo_campos.setVisible(false);
    }//GEN-LAST:event_Terminar_camposMouseClicked

    private void Abrir_archivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Abrir_archivoMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("./");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archvivos de Texto", "txt");
        jfc.setFileFilter(filtro);
        System.out.println("filtro");
        System.out.println(filtro);
        int seleccion = jfc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            archivo = jfc.getSelectedFile();
            //System.out.println(archivo.getName());
            metadata = leer_archivo.main(archivo.getName());
            System.out.println("leer");
            System.out.println(metadata.getRegistros());
        } else {
            JOptionPane.showMessageDialog(this, "no se pudo abrir ningun archivo");
        }
    }//GEN-LAST:event_Abrir_archivoMouseClicked

    private void Listar_CamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Listar_CamposMouseClicked
        Menu_campos.setVisible(false);
        JTable temp = new JTable();
        DefaultTableModel model = (DefaultTableModel) temp.getModel();
        model.addColumn("Nombre");
        model.addColumn("Tipo");
        temp.setModel(model);
        metadata = leer_archivo.main(archivo.getName());
        // System.out.println(metadata.getNum_campos() + "sadasd");
        for (int i = 0; i < metadata.getLista_campos().size(); i++) {
            Object[] regi = new Object[2];
            regi[0] = metadata.getLista_campos().get(i).getNombre();
            regi[1] = metadata.getLista_campos().get(i).getTipo();
            model.addRow(regi);
        }
        temp.setModel(model);
        jTable1.setModel(temp.getModel());
        listar_campos.pack();
        listar_campos.setLocationRelativeTo(null);
        listar_campos.setVisible(true);

    }//GEN-LAST:event_Listar_CamposMouseClicked

    private void elim_campoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elim_campoMouseClicked
        int delete = -1;
        delete = jTable1.getSelectedRow();
        if (delete != -1) {
            if (delete == 0) {
                JOptionPane.showMessageDialog(this, "no se puede borrar el campo llave");
            } else {
                metadata.getLista_campos().remove(delete);
                metadata.setNum_campos(metadata.getNum_campos() - 1);
                JOptionPane.showMessageDialog(this, "campo eliminado");
                leer_archivo.escribir(metadata, archivo);
                listar_campos.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "seleccione algo de la lista ");
        }
    }//GEN-LAST:event_elim_campoMouseClicked

    private void mod_campoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mod_campoMouseClicked
        posModificar = -1;
        posModificar = jTable1.getSelectedRow();
        if (posModificar == -1) {
            JOptionPane.showMessageDialog(this, "no ha selecciilnado");

        } else if (posModificar == 0) {
            JOptionPane.showMessageDialog(this, "no se puede modificar la llave");
        } else if (posModificar > 0) {
            Modificar_campos.setModal(true);
            Modificar_campos.pack();
            Modificar_campos.setLocationRelativeTo(this);
            Modificar_campos.setVisible(true);
        }
    }//GEN-LAST:event_mod_campoMouseClicked

    private void Termina_modMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Termina_modMouseClicked
        boolean verificar = false;
        for (int i = 0; i < metadata.getLista_campos().size(); i++) {
            if (metadata.getLista_campos().get(i).getNombre().equals(tf_mod_campo.getText())) {
                verificar = true;
                Tx_campo.setText("");
                posModificar = i;
            }
        }
        if (verificar) {
            JOptionPane.showMessageDialog(this, "Ya existe campo con ese nombre");
        } else {
            metadata.getLista_campos().get(posModificar).setNombre(tf_mod_campo.getText());
            metadata.getLista_campos().get(posModificar).setTipo(combo_tipo2.getSelectedItem().toString());
            leer_archivo.escribir(metadata, archivo);
            JOptionPane.showMessageDialog(this, "se modifico de forma correcta");
        }
        Modificar_campos.setVisible(false);
        listar_campos.setVisible(false);
    }//GEN-LAST:event_Termina_modMouseClicked

    private void tf_mod_campoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_mod_campoMouseClicked
        tf_mod_campo.setText("");
    }//GEN-LAST:event_tf_mod_campoMouseClicked

    private void Agrega_campoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agrega_campoMouseClicked
        if (metadata.getRegistros() == true) {
            JOptionPane.showMessageDialog(jPanel1, "No se puede agregar campos \nsi ya hay registros");
        } else {
            Agregar_campos.setModal(true);
            Agregar_campos.pack();
            Agregar_campos.setVisible(true);
        }
    }//GEN-LAST:event_Agrega_campoMouseClicked

    private void nombre_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_agregarMouseClicked
        nombre_agregar.setText("");
    }//GEN-LAST:event_nombre_agregarMouseClicked

    private void Boton_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_agregarMouseClicked
        String campo = nombre_agregar.getText();
        int pos = Combo_Agrega.getSelectedIndex();
        String tipo = "";
        if (pos == 0) {
            tipo = "int";
        } else if (pos == 1) {
            tipo = "String";
        } else if (pos == 2) {
            tipo = "Char";
        } else if (pos == 3) {
            tipo = "boolean";
        }
        metadata.getLista_campos().add(new Campos(campo, tipo));
        metadata.setNum_campos(metadata.getNum_campos() + 1);
        leer_archivo.escribir(metadata, archivo);
        JOptionPane.showMessageDialog(Agregar_campos, "se agrego con exito.");
        Agregar_campos.setVisible(false);
        listar_campos.setVisible(false);
    }//GEN-LAST:event_Boton_agregarMouseClicked

    private void crear_regisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crear_regisMouseClicked

        try {
            RandomAccessFile f = new RandomAccessFile(archivo, "rw");
            System.out.println("boton");
            Registros regis_temp = new Registros();
            ArrayList lista = new ArrayList();
            regis_temp.setNum_camp(metadata.getNum_campos());
            regis_temp.setTama(metadata.getNum_campos());
            System.out.println(metadata.getNum_campos());
            System.out.println("antes for");
            for (int i = 0; i < metadata.getNum_campos(); i++) {
                System.out.println("en");
                System.out.println(metadata.getLista_campos().get(i).getTipo());
                if ("int".equals(metadata.getLista_campos().get(i).getTipo())) {
                    int numero = Integer.parseInt(JOptionPane.showInputDialog(Registros, "campo llave \ningrese un " + metadata.getLista_campos().get(i).getTipo() + " para el campo " + metadata.getLista_campos().get(i).getNombre()));
                    lista.add(numero);
                } else if ("String".equals(metadata.getLista_campos().get(i).getTipo())) {
                    String cadena = JOptionPane.showInputDialog(Registros, "campo llave \ningrese un " + metadata.getLista_campos().get(i).getTipo() + " para el campo " + metadata.getLista_campos().get(i).getNombre());
                    lista.add(cadena);
                } else if ("Char".equals(metadata.getLista_campos().get(i).getTipo())) {
                    String caracter = JOptionPane.showInputDialog(Registros, "campo llave \ningrese un " + metadata.getLista_campos().get(i).getTipo() + " para el campo " + metadata.getLista_campos().get(i).getNombre());
                    char car = caracter.charAt(0);
                    lista.add(car);
                } else if ("boolean".equals(metadata.getLista_campos().get(i).getTipo())) {
                    int bool = Integer.parseInt(JOptionPane.showInputDialog(Registros, "campo llave \ningrese un " + metadata.getLista_campos().get(i).getTipo() + " para el campo " + metadata.getLista_campos().get(i).getNombre()) + "\n 1) para true otro numero para false");
                    boolean real;
                    if (bool == 1) {
                        real = true;
                    } else {
                        real = false;
                    }
                    lista.add(real);
                } else {
                    System.out.println("no entra a los if");
                }
            }
            System.out.println("pointer antes " + f.getFilePointer());
            //long pos= archivo.getTotalSpace()-archivo.getFreeSpace();
            f.seek(200);
            int Cadena=f.read();
//            long posicion = f.readLong();
            //f.seek(posicion);
            System.out.println(Cadena+"  asd");
            for (int i = 0; i < lista.size(); i++) {
                f.writeBytes(lista.get(i) + ",");
            }
            f.writeBytes(";");
            System.out.println("pointer" + f.getFilePointer());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(P_Grafica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(P_Grafica.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_crear_regisMouseClicked

    private void buscar_regisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar_regisMouseClicked

    }//GEN-LAST:event_buscar_regisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P_Grafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P_Grafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P_Grafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P_Grafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P_Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abrir_archivo;
    private javax.swing.JButton Agrega_campo;
    private javax.swing.JDialog Agregar_campos;
    private javax.swing.JLabel Archivo_guardar;
    private javax.swing.JLabel Archivo_nuevo;
    private javax.swing.JLabel Archivos_salir;
    private javax.swing.JButton BT_Agrega_campo;
    private javax.swing.JButton Boton_agregar;
    private javax.swing.JComboBox<String> Combo_Agrega;
    private javax.swing.JComboBox<String> Combo_tipo;
    private javax.swing.JLabel L_Fondo;
    private javax.swing.JLabel L_archivos;
    private javax.swing.JLabel L_campos;
    private javax.swing.JLabel L_registro;
    private javax.swing.JLabel L_salir;
    private javax.swing.JLabel Listar_Campos;
    private javax.swing.JDialog Menu_archivos;
    private javax.swing.JDialog Menu_campos;
    private javax.swing.JDialog Modificar_campos;
    private javax.swing.JDialog Nuevo_campos;
    private javax.swing.JLabel Nuevo_registro;
    private javax.swing.JDialog Registros;
    private javax.swing.JLabel Reindexar;
    private javax.swing.JButton Termina_mod;
    private javax.swing.JButton Terminar_campos;
    private javax.swing.JTextField Tx_campo;
    private javax.swing.JToggleButton buscar_regis;
    private javax.swing.JComboBox<String> combo_tipo2;
    private javax.swing.JToggleButton crear_regis;
    private javax.swing.JButton elim_campo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog listar_campos;
    private javax.swing.JToggleButton listar_regis;
    private javax.swing.JButton mod_campo;
    private javax.swing.JTextField nombre_agregar;
    private javax.swing.JTextField tf_mod_campo;
    private javax.swing.JLabel utilidades;
    // End of variables declaration//GEN-END:variables
ArrayList<Campos> temp = new ArrayList();
    Metadata metadata = new Metadata();
    File archivo = null;
    boolean nuevo = false;
    int posModificar = -1;
    Arbol_B tree = new Arbol_B();
    //ArrayList<dispo> availist = new ArrayList();
    ArrayList<Registros> registros = new ArrayList<>();
}
