/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructuras_2;

import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class P_Grafica extends javax.swing.JFrame {

    /**
     * Creates new form P_Grafica
     */
    File Archivo = null;

    public P_Grafica() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_archivos = new javax.swing.JDialog();
        Archivo_guardar = new javax.swing.JLabel();
        Archivo_nuevo = new javax.swing.JLabel();
        Abrir_archivo = new javax.swing.JLabel();
        Archivos_salir = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Menu_campos = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        Nuevo_registro = new javax.swing.JLabel();
        modificar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Nuevo_campos = new javax.swing.JDialog();
        Combo_tipo = new javax.swing.JComboBox<>();
        Tx_campo = new javax.swing.JTextField();
        BT_Agrega_campo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        Terminar_campos = new javax.swing.JButton();
        listar_campos = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        L_campos = new javax.swing.JLabel();
        L_archivos = new javax.swing.JLabel();
        Reindexar = new javax.swing.JLabel();
        utilidades = new javax.swing.JLabel();
        L_registro = new javax.swing.JLabel();
        L_salir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        L_Fondo = new javax.swing.JLabel();

        Menu_archivos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Archivo_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        Menu_archivos.getContentPane().add(Archivo_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        Archivo_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NuevoArchivo.png"))); // NOI18N
        Archivo_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Archivo_nuevoMouseClicked(evt);
            }
        });
        Menu_archivos.getContentPane().add(Archivo_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        Abrir_archivo.setForeground(new java.awt.Color(255, 255, 255));
        Abrir_archivo.setText("ABRIR ARCHIVO FALTA FOTO");
        Abrir_archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Abrir_archivoMouseClicked(evt);
            }
        });
        Menu_archivos.getContentPane().add(Abrir_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 90));

        Archivos_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Archivos_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Archivos_salirMouseClicked(evt);
            }
        });
        Menu_archivos.getContentPane().add(Archivos_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo archivos.jpg"))); // NOI18N
        Menu_archivos.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 650));

        Menu_campos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listarCampos.png"))); // NOI18N
        Menu_campos.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        Nuevo_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo campo.png"))); // NOI18N
        Nuevo_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nuevo_registroMouseClicked(evt);
            }
        });
        Menu_campos.getContentPane().add(Nuevo_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        Menu_campos.getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondocampos.jpg"))); // NOI18N
        Menu_campos.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Nuevo_campos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Int", "String", "Char", "Boolean" }));
        Nuevo_campos.getContentPane().add(Combo_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 90, 90, 40));

        Tx_campo.setText("Nombre del Campo");
        Tx_campo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tx_campoMouseClicked(evt);
            }
        });
        Nuevo_campos.getContentPane().add(Tx_campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 40));

        BT_Agrega_campo.setText("Agregar");
        BT_Agrega_campo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_Agrega_campoMouseClicked(evt);
            }
        });
        Nuevo_campos.getContentPane().add(BT_Agrega_campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Creacion de Campos");
        Nuevo_campos.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        Nuevo_campos.getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, 279));

        Terminar_campos.setText("terminar de agregar");
        Terminar_campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Terminar_camposMouseClicked(evt);
            }
        });
        Nuevo_campos.getContentPane().add(Terminar_campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );

        listar_campos.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_campos.setBackground(new java.awt.Color(255, 255, 255));
        L_campos.setForeground(new java.awt.Color(255, 204, 102));
        L_campos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campos.png"))); // NOI18N
        L_campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_camposMouseClicked(evt);
            }
        });
        getContentPane().add(L_campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 130));

        L_archivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/File_Explorer_23583.png"))); // NOI18N
        L_archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_archivosMouseClicked(evt);
            }
        });
        getContentPane().add(L_archivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        Reindexar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arbol.png"))); // NOI18N
        Reindexar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReindexarMouseClicked(evt);
            }
        });
        getContentPane().add(Reindexar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        utilidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xml.png"))); // NOI18N
        utilidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilidadesMouseClicked(evt);
            }
        });
        getContentPane().add(utilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        L_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N
        L_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_registroMouseClicked(evt);
            }
        });
        getContentPane().add(L_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, -1, -1));

        L_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        L_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_salirMouseClicked(evt);
            }
        });
        getContentPane().add(L_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RICARDO ROMERO 11641137");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BRAULIO CALIX 11711133");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROYECTO ESTRUCTURAS DE DATOS II ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        L_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpg"))); // NOI18N
        getContentPane().add(L_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_salirMouseClicked
        JOptionPane.showMessageDialog(this, "Gracias por usar el mejor \nmanejador de archivos ;)");
        System.exit(0);
    }//GEN-LAST:event_L_salirMouseClicked

    private void L_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_registroMouseClicked
        JOptionPane.showMessageDialog(this, "opcion no implementada..... aún ;)");
    }//GEN-LAST:event_L_registroMouseClicked

    private void utilidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilidadesMouseClicked
        JOptionPane.showMessageDialog(this, "opcion no implementada..... aún ;)");
    }//GEN-LAST:event_utilidadesMouseClicked

    private void ReindexarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReindexarMouseClicked
        JOptionPane.showMessageDialog(this, "opcion no implementada..... aún ;)");
    }//GEN-LAST:event_ReindexarMouseClicked

    private void L_archivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_archivosMouseClicked
        Menu_archivos.setModal(true);
        Menu_archivos.pack();
        Menu_archivos.setLocationRelativeTo(this);
        Menu_archivos.setVisible(true);
    }//GEN-LAST:event_L_archivosMouseClicked

    private void L_camposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_camposMouseClicked
        Menu_campos.setModal(true);
        Menu_campos.pack();
        Menu_campos.setLocationRelativeTo(this);
        Menu_campos.setVisible(true);
    }//GEN-LAST:event_L_camposMouseClicked

    private void Archivo_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Archivo_nuevoMouseClicked
        JFileChooser fileChooser = new JFileChooser("./");
        fileChooser.setDialogTitle("Seleccione");
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            archivo = new File(fileChooser.getSelectedFile().getPath() + ".txt");

            if (!archivo.exists()) {
                try {
                    archivo.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(P_Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(Menu_archivos, "Archivo Creado");
            } else {
                JOptionPane.showMessageDialog(Menu_archivos, "Arhcivo con ese nombre ya existe");
            }
        }
    }//GEN-LAST:event_Archivo_nuevoMouseClicked

    private void Tx_campoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tx_campoMouseClicked
        // TODO add your handling code here:
        Tx_campo.setText("");
    }//GEN-LAST:event_Tx_campoMouseClicked

    private void Nuevo_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nuevo_registroMouseClicked
        Nuevo_campos.setModal(true);
        Nuevo_campos.pack();
        Nuevo_campos.setLocationRelativeTo(this);
        Nuevo_campos.setVisible(true);
    }//GEN-LAST:event_Nuevo_registroMouseClicked

    private void Archivos_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Archivos_salirMouseClicked
        Menu_archivos.setVisible(false);
    }//GEN-LAST:event_Archivos_salirMouseClicked

    private void BT_Agrega_campoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Agrega_campoMouseClicked
        String campo = Tx_campo.getText();
        int pos = Combo_tipo.getSelectedIndex();
        System.out.println(Combo_tipo.getSelectedIndex());
        String tipo = "";
        if (pos == 0) {
            tipo = "int";
        } else if (pos == 1) {
            tipo = "String";
        } else if (pos == 2) {
            tipo = "Char";
        } else if (pos == 3) {
            tipo = "boolean";
        }
        JOptionPane.showMessageDialog(Nuevo_campos, "Campo agregado con exito ");
        Tx_campo.setText("Nombre del Campo");
        temp.add(new Campos(campo, tipo));
        String Mensaje = "" + temp.size() + ";0;1;";
        for (int i = 0; i < temp.size(); i++) {
            Mensaje += temp.get(i).toString();
        }
        Mensaje += ";";
        try {
            FileWriter fw = new FileWriter(archivo);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(Mensaje);
            bw.close();

        } catch (IOException ex) {
            Logger.getLogger(P_Grafica.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BT_Agrega_campoMouseClicked

    private void Terminar_camposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Terminar_camposMouseClicked
        String Mensaje = "";
        for (int i = 0; i < temp.size(); i++) {
            Mensaje += i + ") ";
            Mensaje += temp.get(i).toString();
            Mensaje += "\n";
        }
        int numero = -1;
        while (numero < 0 || numero > temp.size() - 1) {
            try {
                numero = Integer.parseInt(JOptionPane.showInputDialog(Nuevo_campos, "ingrese el numero del campo que desea que sea la llave: \n" + Mensaje));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        Nuevo_campos.setVisible(false);
    }//GEN-LAST:event_Terminar_camposMouseClicked

    private void Abrir_archivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Abrir_archivoMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("./");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archvivos de Texto", "txt");
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            Archivo = jfc.getSelectedFile();
        }

        metadata = leer_archivo.main(Archivo.getName());
        for (int i = 0; i < metadata.getLista_campos().size(); i++) {
            System.out.println("" + metadata.getLista_campos().get(i).toString());
        }

    }//GEN-LAST:event_Abrir_archivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P_Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P_Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P_Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P_Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P_Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abrir_archivo;
    private javax.swing.JLabel Archivo_guardar;
    private javax.swing.JLabel Archivo_nuevo;
    private javax.swing.JLabel Archivos_salir;
    private javax.swing.JButton BT_Agrega_campo;
    private javax.swing.JComboBox<String> Combo_tipo;
    private javax.swing.JLabel L_Fondo;
    private javax.swing.JLabel L_archivos;
    private javax.swing.JLabel L_campos;
    private javax.swing.JLabel L_registro;
    private javax.swing.JLabel L_salir;
    private javax.swing.JDialog Menu_archivos;
    private javax.swing.JDialog Menu_campos;
    private javax.swing.JDialog Nuevo_campos;
    private javax.swing.JLabel Nuevo_registro;
    private javax.swing.JLabel Reindexar;
    private javax.swing.JButton Terminar_campos;
    private javax.swing.JTextField Tx_campo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog listar_campos;
    private javax.swing.JLabel modificar;
    private javax.swing.JLabel utilidades;
    // End of variables declaration//GEN-END:variables
ArrayList<Campos> temp = new ArrayList();
    Metadata metadata = new Metadata();
    File archivo=null;
}
